# Generated by Django 4.1.4 on 2022-12-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_likes_content_type_likes_object_id_likes_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-value'],
            },
        ),
        migrations.AlterField(
            model_name='rating',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='IP adress'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.ratingstar', verbose_name='star'),
            preserve_default=False,
        ),
    ]
