# Generated by Django 4.1.4 on 2022-12-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_ratingstar_alter_rating_ip_alter_rating_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='ip',
        ),
    ]
