# Generated by Django 4.1.4 on 2022-12-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_rating_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
