# Generated by Django 4.1.4 on 2022-12-12 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_ratingstar_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.PositiveIntegerField(default=10, help_text='Rate the movie from 0 to 10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
