# Generated by Django 4.1.4 on 2022-12-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_rating_star_delete_ratingstar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='star',
        ),
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.PositiveIntegerField(choices=[(1, 'Bad'), (2, 'Ok'), (3, 'Fine'), (4, 'Good'), (5, 'Amazing')], default=1),
            preserve_default=False,
        ),
    ]
