# Generated by Django 4.1.4 on 2022-12-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_rating_star_rating_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rate',
            new_name='star',
        ),
    ]
